# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
spring:
  datasource:
    url: jdbc:h2:mem:spring_boot_oauth2
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: classpath:/data.sql
    
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database : H2
    openInView : false
    show-sql : true
    generate-ddl: false
    hibernate.ddl-auto : none

spring.h2.console:
  enabled: true
  path: /h2-console


security:
  user: 
    name: user
    password: test
    
  oauth2:
    client:
      client-id: foo
      client-secret: bar
#    authorization:
#      token-key-access: isAuthenticated()


logging.level:
  org.springframework:
    security: debug
    boot: debug
